### ISSUE TITLE
Please add py-lxml

### ISSUE THREAD

**Issue by Groofster** [linuxserver/docker-hydra#10]
Please add py-lxml to the container. It makes formatting the results a lot faster. (selecting it as "Html parser" in "config -> searching" is also necessary)

In the meantime have added to the container via:

docker exec -it hydra apk --update add py-lxml

**Comment by sparklyballs** [comment]
it's in the baseimage this image uses

https://github.com/linuxserver/docker-baseimage-alpine-python/blob/master/Dockerfile#L16

**Comment by Groofster** [comment]
Oeps, I need to do a better job at RTFM'ing......
