### ISSUE TITLE
Blank grey screen with IE, Chrome, Mozilla

### ISSUE THREAD

**Issue by Sneeks09** [linuxserver/docker-hydra#13]
Hi,
If I start the docker container and connect to nzbhydra I get a grey screen with no content.
HTML source seems to be ok on the first review. 
Chrome console reports:
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH -- alllibs.js
Uncaught ReferenceError: angular is not defined at nzbhydra.js:1 -- nzbhydra.js:1
Uncaught ReferenceError: apiCheck is not defined at containerIP/:46 -- containerIP/:46

Logs:
2017-09-16 11:10:01,733 - NOTICE - nzbhydra - MainThread - Starting NZBHydra 0.2.226
2017-09-16 11:10:01,733 - NOTICE - nzbhydra - MainThread - Base path is /app/hydra
2017-09-16 11:10:01,733 - NOTICE - nzbhydra - MainThread - Loading settings from /config/hydra/settings.cfg
2017-09-16 11:10:01,738 - INFO - log - MainThread - Logging to file /config/hydra/nzbhydra.log as defined in the command line
2017-09-16 11:10:01,739 - INFO - log - MainThread - Setting umask of log file /config/hydra/nzbhydra.log to 0640
2017-09-16 11:10:01,739 - INFO - nzbhydra - MainThread - Started
2017-09-16 11:10:01,740 - INFO - nzbhydra - MainThread - Loading database file /config/hydra/nzbhydra.db
2017-09-16 11:10:01,740 - INFO - database - MainThread - Initializing database and creating tables
2017-09-16 11:10:01,748 - INFO - database - MainThread - Created new version info entry with database version 21
2017-09-16 11:10:02,164 - INFO - nzbhydra - MainThread - Starting db
2017-09-16 11:10:02,166 - INFO - indexers - MainThread - Unable to find indexer with name anizb in database. Will add it
2017-09-16 11:10:02,194 - INFO - indexers - MainThread - Unable to find indexer with name Binsearch in database. Will add it
2017-09-16 11:10:02,229 - INFO - indexers - MainThread - Activated indexer Binsearch
2017-09-16 11:10:02,231 - INFO - indexers - MainThread - Unable to find indexer with name NZBClub in database. Will add it
2017-09-16 11:10:02,257 - INFO - indexers - MainThread - Activated indexer NZBClub
2017-09-16 11:10:02,259 - INFO - indexers - MainThread - Unable to find indexer with name NZBIndex in database. Will add it
2017-09-16 11:10:02,294 - INFO - indexers - MainThread - Activated indexer NZBIndex
2017-09-16 11:10:02,295 - NOTICE - nzbhydra - MainThread - Starting web app on 127.0.0.1:5075
2017-09-16 11:10:02,295 - NOTICE - nzbhydra - MainThread - Go to http://127.0.0.1:5075 for the frontend
2017-09-16 11:10:02,300 - INFO - web - MainThread - Running threaded server

**Comment by sparklyballs** [comment]
fresh pull using this run line

`docker run -d --name=test -p 5075:5075 -e TZ=Europe/London -v /home/sparklyballs/test:/config -v /home/sparklyballs/test/downloads:/downloads -e PGID=1000 -e PUID=1000 linuxserver/hydra`

results in using safari browser. 

![screen shot 2017-09-16 at 10 38 43](https://user-images.githubusercontent.com/4343808/30511172-5d55ea90-9acb-11e7-9034-b4a978189331.png)

**Comment by Sneeks09** [comment]
Thank you, but same result.
![docker](https://user-images.githubusercontent.com/29660724/30511350-53523ed4-9ad7-11e7-9141-524fdd44cc05.PNG)

![firefox](https://user-images.githubusercontent.com/29660724/30511354-6a5a080a-9ad7-11e7-8739-1fa3e954ecf3.PNG)

![chrome](https://user-images.githubusercontent.com/29660724/30511357-8d2a074a-9ad7-11e7-91dd-2847d44c6ff7.PNG)

**Comment by Sneeks09** [comment]
Safari for Win7
![safari](https://user-images.githubusercontent.com/29660724/30511402-6b605668-9ad8-11e7-8d17-eb1c64112631.PNG)

**Comment by j0nnymoe** [comment]
Please can you provide more information about your setup, such as host OS / docker create/run commands etc.

**Comment by Sneeks09** [comment]
Hi,
my last comment was with the recommended command:
docker run -d --name=test -p 5075:5075 -e TZ=Europe/London -v /home/sparklyballs/test:/config -v /home/sparklyballs/test/downloads:/downloads -e PGID=1000 -e PUID=1000 linuxserver/hydra 

My initial comment was with docker-compose
version: '3.2'
services:
    nzbhydra:
        container_name: nzbhydra
        image: "linuxserver/hydra"
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "5"
        ports:
            - "5075:5075"
        volumes:
            - type: mount
              source: NZB
              target: /downloads
              shared: true
            - /etc/localtime:/etc/localtime:ro
            - /var/log/nzbhydra:/config/hydra
            - /root/.bashrc:/root/.bashrc
            - /etc/nzbhydra:/config/hydra
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Europe/Berlin
        hostname: debianDB
        domainname: micropearl.info
        dns_search: micropearl.info
        networks:
            webNet:
                ipv4_address: 172.30.0.6
        restart: always

networks:
    webNet:
        external:
            name: webNet
            
volumes:
    NZB:
        driver: local
        driver_opts:
            type: nfs
            o: proto=tcp,addr=192.168.3.103,rw
            device: ":/mnt/Daten/USENext/nzb"

I will try again with hostname: nzbhydra

Maybe this could be an issue

**Comment by Sneeks09** [comment]
Docker Host:
root@debianDocker:/home/docker# cat /etc/issue
Debian GNU/Linux 8 \n \l

root@debianDocker:/home/docker# docker info
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 70
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 200
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.747GiB
Name: debianDocker
ID: QZ7M:I3PH:UUHV:RW6L:DJ2E:UWXQ:N4NH:PN6T:QINB:OVGW:ITSV:ZQ7P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: sneeks09
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period Support

But i think it is no docker issue. HTML code from browser:
<!DOCTYPE html>
<html ng-app="nzbhydraApp">
<head>
    <title ng-bind="'NZB Hydra' + ((' - ' + title) || '')">NZB Hydra</title>
    <base href="/"/>
    <meta name="robots" content="noindex"/>
    <meta name="referrer" content="no-referrer"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="static/css/alllibs.css" rel="stylesheet">
    <link href="static/css/grey.css" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="static/img/favicon.ico">

<script type="text/javascript" src="http://ie.kis.scr.kaspersky-labs.com/1B74BD89-2A22-4B93-B451-1C9E1052A0EC/main.js" charset="UTF-8"></script></head>
<body style="text-align: center">
<div growl></div>

    <div id="wrap" ng-cloak>

        <div ui-view="header"></div>


        <div style="margin: auto; max-width: 1400px;">
            <div id="banner"></div>
            <div class="container-fluid" block-ui="main" ui-view="container">
            </div>
        </div>
        <div id="push"></div>
    </div>

<span ng-controller="UpdateFooterController">
    <div id="footer" ng-if="updateAvailable" ng-cloak>
        <div class="container">
            Yay, there's an update available. Your version: <span ng-bind-html="currentVersion"></span>. Latest version: <span ng-bind-html="repVersion"></span>.
            <button class="btn btn-default" type="button" ng-click="showChangelog()" style="margin-top: 5px;">See what's new!</button>
            <button class="btn btn-default" type="button" ng-click="update()" style="margin-top: 5px;">Update now!</button>
        </div>

    </div>
</span>

</body>

<script src="static/js/alllibs.js"></script>
<script src="static/js/nzbhydra.js"></script>
<script type="application/javascript">
    apiCheck.globalConfig.disabled = true;
    window.onProd = true;
    angular.module("nzbhydraApp").constant("bootstrapped", {"username": null, "authType": "none", "maySeeSearch": true, "adminRestricted": false, "statsRestricted": false, "maySeeStats": true, "searchRestricted": false, "maySeeDetailsDl": true, "maySeeAdmin": true, "authConfigured": false, "showIndexerSelection": true, "safeConfig": {"indexers": [{"showOnSearch": true, "preselect": true, "enabled": false, "name": "anizb", "categories": ["anime"]}, {"showOnSearch": true, "preselect": true, "enabled": true, "name": "Binsearch", "categories": []}, {"showOnSearch": true, "preselect": true, "enabled": true, "name": "NZBClub", "categories": []}, {"showOnSearch": true, "preselect": true, "enabled": true, "name": "NZBIndex", "categories": []}], "firstStart": 1505553000, "authType": "none", "pollShown": 0, "dereferer": "http://www.dereferer.org/?$s", "searching": {"alwaysShowDuplicates": false, "enableCategorySizes": true, "maxAge": ""}, "categories": [{"applyRestrictions": false, "mayBeSelected": false, "ignoreResults": "never", "supportsById": false, "requiredRegex": null, "forbiddenRegex": null, "forbiddenWords": null, "pretty": "N/A", "requiredWords": null, "newznabCategories": [], "name": "na"}, {"applyRestrictions": false, "mayBeSelected": true, "ignoreResults": false, "supportsById": false, "requiredRegex": null, "forbiddenRegex": null, "forbiddenWords": null, "pretty": "All", "requiredWords": null, "newznabCategories": [], "name": "all"}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": true, "max": 20000, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "movies", "min": 500, "requiredRegex": null, "pretty": "Movies", "requiredWords": null, "newznabCategories": [2000]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": true, "max": 20000, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "movieshd", "min": 3000, "requiredRegex": null, "pretty": "Movies HD", "requiredWords": null, "newznabCategories": [2040, 2050, 2060]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": true, "max": 3000, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "moviessd", "min": 500, "requiredRegex": null, "pretty": "Movies SD", "requiredWords": null, "newznabCategories": [2030]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": true, "max": 5000, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "tv", "min": 50, "requiredRegex": null, "pretty": "TV", "requiredWords": null, "newznabCategories": [5000]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": true, "max": 4500, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "tvhd", "min": 300, "requiredRegex": null, "pretty": "TV HD", "requiredWords": null, "newznabCategories": [5040]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": true, "max": 1000, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "tvsd", "min": 50, "requiredRegex": null, "pretty": "TV SD", "requiredWords": null, "newznabCategories": [5030]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": false, "max": 15000, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "anime", "min": 50, "requiredRegex": null, "pretty": "Anime", "requiredWords": null, "newznabCategories": [5070]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": false, "max": 2000, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "audio", "min": 1, "requiredRegex": null, "pretty": "Audio", "requiredWords": null, "newznabCategories": [3000]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": false, "max": 2000, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "flac", "min": 10, "requiredRegex": null, "pretty": "Audio FLAC", "requiredWords": null, "newznabCategories": [3040]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": false, "max": 500, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "mp3", "min": 1, "requiredRegex": null, "pretty": "Audio MP3", "requiredWords": null, "newznabCategories": [3010]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": false, "max": 1000, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "audiobook", "min": 50, "requiredRegex": null, "pretty": "Audiobook", "requiredWords": null, "newznabCategories": [3030]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": false, "max": 40000, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "console", "min": 100, "requiredRegex": null, "pretty": "Console", "requiredWords": null, "newznabCategories": [1000]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": false, "max": 50000, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "pc", "min": 100, "requiredRegex": null, "pretty": "PC", "requiredWords": null, "newznabCategories": [4000]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": false, "max": 10000, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "both", "name": "xxx", "min": 100, "requiredRegex": null, "pretty": "XXX", "requiredWords": null, "newznabCategories": [6000]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": false, "max": 100, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "ebook", "min": null, "requiredRegex": null, "pretty": "Ebook", "requiredWords": null, "newznabCategories": [7020, 8010]}, {"applyRestrictions": "both", "mayBeSelected": true, "supportsById": false, "max": 250, "forbiddenRegex": null, "forbiddenWords": [], "ignoreResults": "never", "name": "comic", "min": 1, "requiredRegex": null, "pretty": "Comic", "requiredWords": null, "newznabCategories": [7030]}], "downloaders": []}});
</script>


</html>

![chrome](https://user-images.githubusercontent.com/29660724/30511511-e1523bc8-9ada-11e7-93c3-c9aefb471ad0.PNG)

**Comment by sparklyballs** [comment]
looks to me that kaspersky is faffing things up

**Comment by Sneeks09** [comment]
Damn, your are right. I´ve overseen this:
<script type="text/javascript" src="http://ie.kis.scr.kaspersky-labs.com/1B74BD89-2A22-4B93-B451-1C9E1052A0EC/main.js" charset="UTF-8"></script>

Now it´s working:
![hydra](https://user-images.githubusercontent.com/29660724/30511592-ce7337e4-9adc-11e7-9a99-160a6deb9f7d.PNG)

Thank you very much for great Support.

**Comment by j0nnymoe** [comment]
Glad you found the issue :)

**Comment by danielo515** [comment]
I am having this same problem, but I do ont have any script messing things up, seems that the hydra docker image is not serving the proper assets and fallbacks to the index page

**Comment by sparklyballs** [comment]
@danielo515 you're lucky i've seen this cos i was specifically checking my emails for something else regarding this image, but you shouldn't necro a closed issue, it's not likely to be seen.  

and me too.... doesn't really tell us anything about your host, docker version, or hell even what browser you're seeing issues with.

i suggest you open a new issue with the relevant information contained.
