### ISSUE TITLE
Config volume mapping

### ISSUE THREAD

**Issue by nightah** [linuxserver/docker-hydra#15]
Arch Linux
docker create --name nzbhydra -v /mnt/NERV01/.config/.nzbhydra:/config -e PUID=0 -e PGID=0 -p 8085:5075 -e TZ=Australia/Melbourne --restart unless-stopped linuxserver/hydra

Just a question regarding the /config volume, it appears in most if not all other similarly designed dockers that the respective configuration files would be expected to live in this volume.

In the service init file the location /config/hydra/* is specified for the config, database and logging. Is this intended or?
Not a huge deal, obvious workaround just means I have to move all the config files in the hydra folder that's created.

Happy for this to be closed if that was a conscious decision.

```
#!/usr/bin/with-contenv bash

cd /config/hydra || exit

exec \
	s6-setuidgid abc python /app/hydra/nzbhydra.py \
	--nobrowser --config /config/hydra/settings.cfg \
	--database /config/hydra/nzbhydra.db \
	--logfile /config/hydra/nzbhydra.log
```

**Comment by j0nnymoe** [comment]
This is by design :)
