### ISSUE TITLE
settings.cfg problem

### ISSUE THREAD

**Issue by kylerw** [linuxserver/docker-hydra#2]
not sure if this is a Docker problem or Hydra problem but on restart/update a new, empty settings.cfg is created and prevents it from starting.

**Comment by lonix** [comment]
Interesting, i will look into this :)

**Comment by lonix** [comment]
well, i run hydra myself, and spun up a new test instance today, in neither cases i could replicate your problem. if you could send me some logs, i would be happy to look futher into it, but for now. im gonna call it a local issue for you.
